name: adhan
description: A Muslim prayer time application using a public API.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add your app dependencies here
  http: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  # These are the testing tools causing your error
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true